# -*- coding: utf-8 -*-
"""onehot_encoding.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a2fpzkeKcp6ML8OhzXioOMlKRgzUBxWH
"""

from google.colab import drive
drive.mount('/content/drive')

!pwd

!ls "/content/drive/My Drive/onehot_encoding_posidex"

import pandas as pd

readdf = pd.read_csv("drive/My Drive/Sample.csv")

readdf.shape

readdf.head()

df = readdf[['MATCH_TYPE_Clean']]

df.shape

df.head()

#new_df = pd.concat([df.drop('MATCH_TYPE_Clean', 1), df['MATCH_TYPE_Clean'].str.get_dummies(sep=",")], 1)
new_df = pd.concat([df, df['MATCH_TYPE_Clean'].str.get_dummies(sep=",")], 1)

new_df.head()

new_df.shape

